spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://175.198.73.174:3306/erp_db
    username: erp_user
    password: erp_qwe123!@#
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
logging:
  level:
    org:
      springframework : INFO
      hibernate:
        sql: TRACE
    com:
      zaxxer:
        hikari: INFO
  file:
    path: ./logs

server:
  port: 8080


#파일 업로드 경로
file-config:
  upload_path: /Users/min/Documents/yh-erp

firebase-config:
  database-url: https://yh-erp.firebaseio.com
  service-key-path: src/main/resources/serviceAccountKey.json
  user-collection-name: user

temp-token: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC80B2sQj3cYd4x\nH/GAE3RzV0/v3fPyd0VNsMiYugFR6VrF5TTngqBRFGEeONgmZj2tdTJQs9UqZxTd\nVYDjHj/vCbWBA82jPlm0xvZSVlVFFQqlKl7C90YVb0YLdr8hT/xCQCfXIB6TP8c+\nYgiYkb3e9sESPLxPxvEkGrHJxJL7yGr4ybAhMiVGdhAHDSwgaYC56DOkCgocGEDV\nVArPn8kfaYsp/A3hFQ1xIRPxeJmDzoInoQQ5VfN+5SV2ZUw7Jz+/wQrVBq+o2l0X\nb2XJ7Azz8hnug/4twKqM0QjZevOTkHbB1lYC1vuB3iDBM0JywC+fi+XF6I7qhluH\nI6+McMdzAgMBAAECggEAMQiNBCypuv9RgAlvIpcq0T9V+5F05j1SKqRj28HGUPrc\nf3MQQ6UZNCUqOXqCq6o2j0LVv76L97iQYxBu6cxzxwSK9cfCkgfBrSBUXLqd51RZ\nEN6JgHFN6ogctSJv7VtDxAK8NfJZ7lyMRieYWuLSX8JODonmT4N3ISyrih36G9eU\nuyyYcfVcENQEbieZSXIUsUKAJoRzV710xqUfB2scnq5XOn6a+oCqocA3++BmSYnl\nNDq51T0MeZbk5Afc9kd9Wq6xXxCjmX3ht/B82a2KVdb2S6mQ9SenAxz0bXtEaEP4\nv+pMXFdqMU3077UmhmbyKrFNyTYyBR22NbU1UzGhcQKBgQDcNH6he5863dm7L13a\nAGw8B5sOUTTN5qvhDr1gnQVZZJL2Z1tOrY29+F2ZA8567BRx3hKaCiDgpbKfXtqd\nzolBdPcWcjtHiNZQaI7VSiUlgsQD3Ra0h3ZcB7qc7A7dyMoyeo5c4nfyDlOX7SiA\nqgBwlAlb+f3EmF7KNtsys9hHQwKBgQDbgUkddFK9jUXziThV2NoqsSfA+TTL4Bh0\n+5ql8qT3CCj1JizvSZ1rZcxldIGlz09oYFxB+pQiFV2Yez2vBCtSaNdbGdXT/Hch\nIoOBYytndIeiWAi7pXQsI2xUtjOg1ft2A902IgllsMISZWFAATU+EaW2mutlYTkE\nupFwVT0EEQKBgQCDBg0u4pK9ARIzqZxrQYMlONVO8Iy90voEYLPYD7YGGazERn1y\n1BuZpHV0vWoXg+8qTZu94jbr1EvzPgpQiXrr4r++sFuLVeVHVN9gE80Eg8lED0Ia\nStvnKIYmJuM1neqJnJimte3urg2ZQXivDfhTBBKJkrcnSg5kvb0xbwdKZwKBgHpW\nbheac1rt1+TJv7oo6D8PCWcF/aT7OuZILIL833BG/fzT0At1beUjkW2iJ3fwOQOl\nYQXs0I7Gdam8Vj6rBjIh+JTvqztA5Gx1PfHpAZHhYo7andNnfX30KDZ2bgPf/wxh\nTvMSuUYR47g5BKCVi8USNNe3NCcGrq6yBMkk2KLhAoGBAIhcmcPNKkWZiwcY+4Of\noAkqS/E9jwfFcl3c6rW2VMydVgsZjv9tXMKFQt2pIRZzhTYbjWm41G32x13xcOdJ\n3NpVOYpodFEBKuaicKVQHcu8lj55/hCQPdeP9czGno5w9vszyHmVgDTepgjKvJA1\nSfLkjEEmehaJNpWXht6Ga9hS\n-----END PRIVATE KEY-----\n"