spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://175.198.73.174:3306/erp_db
    username: erp_user
    password: erp_qwe123!@#
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
logging:
  level:
    org:
      springframework : INFO
      hibernate:
        sql: TRACE
    com:
      zaxxer:
        hikari: INFO
  file:
    path: ./logs

server:
  port: 8080

#파일 업로드 경로
file-config:
  upload_path: /Users/a1234/Documents/yh-erp

firebase-config:
  database-url: https://yh-erp.firebaseio.com
  service-key-path: src/main/resources/serviceAccountKey.json
  user-collection-name: user